import {
  CharacterClass,
  LifeBringerRaces,
  Modes,
  ShadowWalkerRaces,
} from "@rpg-engine/shared/dist/types/character.types";

export const CLASS_BONUS_OR_PENALTIES = [
  {
    class: CharacterClass.None,
    basicAttributes: {
      stamina: 0.3,
      magic: -0.2,
      magicResistance: -0.2,
      strength: 0.2,
      resistance: 0.1,
      dexterity: 0.3,
    },
    combatSkills: {
      first: 0,
      club: 0.2,
      sword: 0.2,
      axe: 0.2,
      distance: -0.2,
      shielding: 0,
      dagger: -0.1,
    },
    craftingSkills: {
      fishing: 0,
      mining: 0,
      lumberjacking: 0.2,
      cooking: 0,
      alchemy: 0,
      blacksmithing: 0,
    },
  },
  {
    class: CharacterClass.Warrior,
    basicAttributes: {
      stamina: 0.3,
      magic: -0.2,
      magicResistance: -0.2,
      strength: 0.2,
      resistance: 0.1,
      dexterity: -0.1,
    },
    combatSkills: {
      first: 0,
      club: 0.2,
      sword: 0.2,
      axe: 0.2,
      distance: -0.2,
      shielding: 0,
      dagger: -0.1,
    },
    craftingSkills: {
      fishing: 0,
      mining: 0,
      lumberjacking: 0.2,
      cooking: 0,
      alchemy: 0,
      blacksmithing: 0,
    },
  },
  {
    class: CharacterClass.Berserker,
    basicAttributes: {
      stamina: 0.3,
      magic: -0.3,
      magicResistance: -0.3,
      strength: 0.4,
      resistance: 0.3,
      dexterity: 0.2,
    },
    combatSkills: {
      first: 0,
      club: 0.1,
      sword: 0.1,
      axe: 0.3,
      distance: -0.3,
      shielding: 0,
      dagger: -0.3,
    },
    craftingSkills: {
      fishing: -0.1,
      mining: 0.2,
      lumberjacking: 0.2,
      cooking: -0.1,
      alchemy: 0.2,
      blacksmithing: 0,
    },
  },
  {
    class: CharacterClass.Druid,
    basicAttributes: {
      stamina: 0.1,
      magic: 0.3,
      magicResistance: 0.3,
      strength: -0.2,
      resistance: -0.2,
      dexterity: -0.1,
    },
    combatSkills: {
      first: 0,
      club: 0.2,
      sword: 0,
      axe: 0,
      distance: -0.1,
      shielding: 0,
      dagger: 0.2,
    },
    craftingSkills: {
      fishing: 0.2,
      mining: 0,
      lumberjacking: 0.1,
      cooking: 0.2,
      alchemy: 0.2,
      blacksmithing: 0,
    },
  },
  {
    class: CharacterClass.Sorcerer,
    basicAttributes: {
      stamina: -0.1,
      magic: 0.4,
      magicResistance: 0.3,
      strength: -0.3,
      resistance: -0.2,
      dexterity: 0,
    },
    combatSkills: {
      first: -0.1,
      club: -0.1,
      sword: -0.1,
      axe: -0.1,
      distance: 0.3,
      shielding: -0.1,
      dagger: -0.1,
    },
    craftingSkills: {
      fishing: -0.1,
      mining: -0.1,
      lumberjacking: 0,
      cooking: 0.1,
      alchemy: 0.2,
      blacksmithing: 0,
    },
  },
  {
    class: CharacterClass.Rogue,
    basicAttributes: {
      stamina: 0.1,
      magic: 0,
      magicResistance: 0.1,
      strength: -0.2,
      resistance: -0.2,
      dexterity: 0.4,
    },
    combatSkills: {
      first: 0,
      club: 0,
      sword: 0.1,
      axe: 0,
      distance: 0.2,
      shielding: -0.1,
      dagger: 0.4,
    },
    craftingSkills: {
      fishing: 0.4,
      mining: 0,
      lumberjacking: 0.1,
      cooking: 0,
      alchemy: 0,
      blacksmithing: 0.1,
    },
  },
  {
    class: CharacterClass.Hunter,
    basicAttributes: {
      stamina: 0,
      magic: 0,
      magicResistance: 0.2,
      strength: 0.1,
      resistance: 0.2,
      dexterity: 0.3,
    },
    combatSkills: {
      first: 0,
      club: 0,
      sword: -0.1,
      axe: -0.1,
      distance: 0.3,
      shielding: 0.3,
      dagger: 0.3,
    },
    craftingSkills: {
      fishing: 0,
      mining: 0.1,
      lumberjacking: 0.4,
      cooking: 0.1,
      alchemy: 0,
      blacksmithing: 0.2,
    },
  },
];

export const RACE_BONUS_OR_PENALTIES = [
  {
    race: ShadowWalkerRaces.Minotaur,
    basicAttributes: {
      stamina: 0,
      magic: -0.2,
      magicResistance: 0.2,
      strength: 0.3,
      resistance: 0.2,
      dexterity: -0.2,
    },
    combatSkills: {
      first: 0.1,
      club: 0.3,
      sword: 0.1,
      axe: 0.3,
      distance: -0.3,
      shielding: 0.1,
      dagger: 0.1,
    },
    craftingSkills: {
      fishing: 0.1,
      mining: 0.1,
      lumberjacking: 0.1,
      cooking: 0.1,
      alchemy: 0.1,
      blacksmithing: 0.1,
    },
  },
  {
    race: ShadowWalkerRaces.Orc,
    basicAttributes: {
      stamina: 0,
      magic: -0.2,
      magicResistance: 0.2,
      strength: 0.2,
      resistance: 0.1,
      dexterity: -0.1,
    },
    combatSkills: {
      first: 0.1,
      club: 0.2,
      sword: 0.1,
      axe: 0.2,
      distance: -0.2,
      shielding: 0.1,
      dagger: 0.1,
    },
    craftingSkills: {
      fishing: 0.2,
      mining: 0.1,
      lumberjacking: 0.1,
      cooking: -0.1,
      alchemy: -0.2,
      blacksmithing: 0,
    },
  },
  {
    race: ShadowWalkerRaces.Human,
    basicAttributes: {
      stamina: 0,
      magic: 0,
      magicResistance: 0,
      strength: 0,
      resistance: 0,
      dexterity: 0,
    },
    combatSkills: {
      first: 0,
      club: 0,
      sword: 0,
      axe: 0,
      distance: 0,
      shielding: 0,
      dagger: 0,
    },
    craftingSkills: {
      fishing: 0,
      mining: 0,
      lumberjacking: 0,
      cooking: 0,
      alchemy: 0,
      blacksmithing: 0,
    },
  },
  {
    race: LifeBringerRaces.Human,
    basicAttributes: {
      stamina: 0,
      magic: 0,
      magicResistance: 0,
      strength: 0,
      resistance: 0,
      dexterity: 0,
    },
    combatSkills: {
      first: 0,
      club: 0,
      sword: 0,
      axe: 0,
      distance: 0,
      shielding: 0,
      dagger: 0,
    },
    craftingSkills: {
      fishing: 0,
      mining: 0,
      lumberjacking: 0,
      cooking: 0,
      alchemy: 0,
      blacksmithing: 0,
    },
  },
  {
    race: LifeBringerRaces.Dwarf,
    basicAttributes: {
      stamina: 0.1,
      magic: -0.1,
      magicResistance: 0.2,
      strength: 0.2,
      resistance: 0.2,
      dexterity: -0.1,
    },
    combatSkills: {
      first: 0.1,
      club: 0.2,
      sword: 0.1,
      axe: 0.2,
      distance: -0.1,
      shielding: 0.1,
      dagger: 0.1,
    },
    craftingSkills: {
      fishing: -0.1,
      mining: 0.2,
      lumberjacking: 0.2,
      cooking: 0.1,
      alchemy: 0.1,
      blacksmithing: 0,
    },
  },
  {
    race: LifeBringerRaces.Elf,
    basicAttributes: {
      stamina: 0,
      magic: 0.1,
      magicResistance: 0.1,
      strength: -0.1,
      resistance: -0.1,
      dexterity: 0.1,
    },
    combatSkills: {
      first: 0.1,
      club: 0.2,
      sword: 0.1,
      axe: -0.1,
      distance: 0.2,
      shielding: 0.1,
      dagger: 0.1,
    },
    craftingSkills: {
      fishing: 0.1,
      mining: 0.1,
      lumberjacking: 0.1,
      cooking: 0.1,
      alchemy: 0.1,
      blacksmithing: 0.1,
    },
  },
];

export const MODE_EXP_MULTIPLIER: { [key in Modes]: number } = {
  [Modes.SoftMode]: 1,
  [Modes.HardcoreMode]: 1.2,
  [Modes.PermadeathMode]: 1.5,
};
