export const TRADER_SELL_PRICE_MULTIPLIER = 0.25;
export const TRADER_BUY_PRICE_MULTIPLIER = 1.75;
export const ITEM_USE_WITH_BASE_EFFECT = 1;
export const ITEM_USE_WITH_BASE_SCALING_FACTOR = 0.008;
export const ITEM_CLEANUP_THRESHOLD = 100;
