export const LOOT_GOLD_RATIO = 1.5;
export const LOOT_GOLD_MAX_HEALTH_WEIGHT = 0.25;
export const LOOT_GOLD_STRENGTH_WEIGHT = 1.5;
export const LOOT_GOLD_RESISTANCE_WEIGHT = 1.5;
export const LOOT_GOLD_SKILLS_WEIGHT = 1;
