export const NPC_BASE_HEALTH_MULTIPLIER = 1.25;
export const NPC_SKILL_LEVEL_MULTIPLIER = 1.5;
export const NPC_SKILL_STRENGTH_MULTIPLIER = 1.5;
export const NPC_SKILL_DEXTERITY_MULTIPLIER = 1.25;
export const NPC_SKILL_RESISTANCE_MULTIPLIER = 1.25;
export const NPC_LOOT_CHANCE_MULTIPLIER = 0.7;
