### 

# Asset :: Create
POST {{baseUrl}}/assets HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "PetrobrasTest",
    "ticker": "PETR31",
    "sector": "Oil and gas",
    "stockExchange": "BOVESPA",
    "country": "Brazil",
    "currency": "BRL",
    "type": "Stock"
}

###

# Asset :: Read
GET {{baseUrl}}/assets/609f772357967e006744a659 HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Asset :: Filter (filterBy)
## Returns a list of assets that matches a specific company
## filterBy: any parameter from AssetModel.ts
## keyword: any string to match against the filter
GET {{baseUrl}}/assets/?keyword=BTC&filterBy=ticker
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Asset :: Filter (name and ticker only)
## Returns a list of assets that matches a specific company
## nameAndTickerOnly: will use the keyword to search for assets using only the name and ticker fields

GET {{baseUrl}}/assets/?keyword=BBAS3&nameAndTickerOnly=true
Authorization: Bearer {{authToken}}
Content-Type: application/json

### 
 