#Factions :: Get Races by Faction
GET {{baseUrl}}/factions/races?faction=Life Bringer HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

#Factions :: Get Sprites by Faction and Race
GET {{baseUrl}}/factions/sprites?faction=Life Bringer&race=Human HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Character :: Create
POST {{baseUrl}}/characters HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Jonit",
  "faction": "Life Bringer",
  "race": "Human",
  "textureKey": "kid-1"
}

###

# Character :: Read
GET {{baseUrl}}/characters/62e84b13583772006349d525 HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Character :: Read All
GET {{baseUrl}}/characters HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Character :: Update
PATCH {{baseUrl}}/characters/631986333577680077faa01a HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Updated Jonit"
}

###

# Character :: Delete
DELETE {{baseUrl}}/characters/6214648d4cca02007d8e5aa6 HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json