# Job Post :: Create 
POST {{baseUrl}}/job-posts HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "title": "Hiring Java Developer ASAP",
    "industry": "Healthcare",
    "description": "This is a sample job post only",
    "workSchedule": "Full-Time",
    "countryCode": "US",
    "city": "California",
    "isFeatured": false,
    "salary": 200000,
    "currency": "USD",
    "skills": ["React", "Redux", "Typescript"],
    "benefits": ["Flexible vacation", "Stock Bonus", "Health Insurance"],
    "workplaceValues": ["Diversity"],
    "workFromAnywhere": true,
    "seniorityLevel": "Intermediate"
}

###

# Job Post :: Read All
GET {{baseUrl}}/job-posts HTTP/1.1
Content-Type: application/json

###

# Job Post :: Read One
GET {{baseUrl}}/job-posts/6166508f80bdd2002f0c0b55 HTTP/1.1
Content-Type: application/json

###

# Job Post :: Update 
PATCH {{baseUrl}}/job-posts/616b599a9c3a0d01036934ad HTTP/1.1
content-type: application/json

{
    "email": "updatedpostemail@gmail.com",
    "countryCode": "CA"
}

###

# Job Post :: Delete
DELETE {{baseUrl}}/job-posts/61635667001dad00b176eb26 HTTP/1.1
Content-Type: application/json
