# Operations :: Fetch NASDAQ tickers 
GET {{baseUrl}}/operations/tickers/NASDAQ HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Operations :: Fetch bovespa tickers
GET {{baseUrl}}/operations/tickers/bovespa HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Operations :: Fetch Bovespa REIT tickers 
GET {{baseUrl}}/operations/tickers/bovespa/REIT HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Operations :: Fetch Cryptocurrency tickers 
GET {{baseUrl}}/operations/tickers/crypto HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

###

# Operations :: Fetch news - Scrap popular news
GET {{baseUrl}}/operations/news/scrap HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

 
###

# Operations :: Push notifications - test
GET {{baseUrl}}/operations/push-notification/test/60cc3c301e176d0051286417 HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json 

###

# Operations :: Company - Update profile
GET {{baseUrl}}/operations/company/609f772657967e006744abda/update/profile HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json 

###

# Operations :: Company - Update ratio ttm
GET {{baseUrl}}/operations/company/609f772657967e006744abda/update/ratio-ttm HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json 

###

# Operations :: Company - Key metrics
GET {{baseUrl}}/operations/company/609f772657967e006744abda/update/key-metrics HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json 

###

# Operations :: Company - Financial Growth
GET {{baseUrl}}/operations/company/609f772657967e006744abda/update/financial-growth HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json 

###

# Operations :: Company - Rating
GET {{baseUrl}}/operations/company/609f772657967e006744abda/update/rating HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json 

###

# Operations :: Company - Enterprise Values
GET {{baseUrl}}/operations/company/609f772657967e006744abda/update/enterprise-values HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json 

###

# Operations :: Company - Discounted Cash Flow
GET {{baseUrl}}/operations/company/609f772657967e006744abda/update/dcf HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json 

###

# Operations :: Company - Market Cap
GET {{baseUrl}}/operations/company/609f772657967e006744abda/update/market-capitalization HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json 

###

# Operations :: Company - Income Statements
GET {{baseUrl}}/operations/company/609f772657967e006744abda/update/income-statements HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json 

###

# Operations :: Company - Key Executives
GET {{baseUrl}}/operations/company/609f772657967e006744abda/update/key-executives HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json 

###

# Operations :: Company - Balance sheet
GET {{baseUrl}}/operations/company/609f772657967e006744abda/update/balance-sheet-statement HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json 

###

# Operations :: Company - Update all
GET {{baseUrl}}/operations/company/update-all HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json 
