### Scripts :: Adjust attack speed
GET {{baseUrl}}/scripts/initial-coordinates HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Remove marketplace junk
GET {{baseUrl}}/scripts/clean-marketplace HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Scripts :: Clean junk items
GET {{baseUrl}}/scripts/cleanup/items HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json
