###

# DB Tasks :: Seed/Update bovespa tickers
GET {{baseUrl}}/db-tasks/tickers/seed/bovespa HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# DB Tasks :: Seed/Update b3 tickers
GET {{baseUrl}}/db-tasks/tickers/seed/b3 HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# DB Tasks :: Seed/Update bovespa (b3) FII
GET {{baseUrl}}/db-tasks/tickers/seed/b3fii HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# DB Tasks :: Seed/Update crypto tickers
GET {{baseUrl}}/db-tasks/tickers/seed/crypto HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# DB Tasks :: Seed/Update Nasdaq/NYSE
GET {{baseUrl}}/db-tasks/tickers/seed/nasdaqnyse HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# DB Tasks :: ETF tickers
GET {{baseUrl}}/db-tasks/tickers/seed/b3etf HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json
